require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'VellarikkaPattanam' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])



  target 'VellarikkaPattanamTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  use_flipper!({ 'Flipper' => '0.74.0' })
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
    end
  end
end

target 'VellarikkaPattanam-tvOS' do
  # Pods for VellarikkaPattanam-tvOS

  target 'VellarikkaPattanam-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'Vellarikka Pattanam' do
   use_react_native!
    pod 'RNShareMenu', :path => '../node_modules/react-native-share-menu'
      # Manually link packages here to keep your extension bundle size minimal
end