require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Ulkka' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  pod 'RNFS', :path => '../node_modules/react-native-fs'

  target 'UlkkaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  #use_flipper!({ 'Flipper' => '0.74.0' })

  #2.3.0 to support firebase/analytics. else app crashes 
  #https://github.com/invertase/react-native-firebase/issues/4935
  
  #use_flipper!({ 'Flipper-Folly' => '2.3.0' }) # uncomment this when atomic_notify one error is gone. else throwing error after updating to 14.5
  # fix for atomic_notify one error after updating to 14.5 start
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })

  # Define find-and-replace function
  def find_and_replace(dir, findstr, replacestr)
    Dir[dir].each do |name|
        text = File.read(name)
        replace = text.gsub(findstr,replacestr)
        replaced = text.index(replacestr)
        if replaced == nil && text != replace
            puts "Fix: " + name
            File.open(name, "w") { |file| file.puts replace }
            STDOUT.flush
        end
    end
    Dir[dir + '*/'].each(&method(:find_and_replace))
  end
# fix for atomic_notify one error after updating to 14.5 end

  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
    end
    #     Fix for Flipper-Folly on iOS 14.5
    find_and_replace("Pods/RCT-Folly/folly/synchronization/DistributedMutex-inl.h",
                   "atomic_notify_one(state)", "folly::atomic_notify_one(state)")

    find_and_replace("Pods/RCT-Folly/folly/synchronization/DistributedMutex-inl.h",
                   "atomic_wait_until(&state, previous | data, deadline)", "folly::atomic_wait_until(&state, previous | data, deadline)")
  end
end

target 'Ulkka-tvOS' do
  # Pods for Ulkka-tvOS

  target 'Ulkka-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'Ulkka-Share' do
   use_react_native!
    pod 'RNShareMenu', :path => '../node_modules/react-native-share-menu'
      # Manually link packages here to keep your extension bundle size minimal
end