name: react-native-android-build-apk
on:
  push:
    tags:
      - v*
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install npm dependencies
        run: |
          yarn
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew
        # Build Command
      - name: Get key store
        run: |
          echo "${{secrets.RELEASE_KEYSTORE}}" > ulkka.keystore.asc
          gpg -d --passphrase "${{secrets.RELEASE_KEYSTORE_PASSPHRASE}}" --batch ulkka.keystore.asc > android/app/ulkka.keystore
          
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease --no-daemon
          
      # Upload to Artifact
#       - name: Upload Artifact
#         uses: actions/upload-artifact@v1
#         with:
#           name: app-release.apk
#           path: android/app/build/outputs/apk/release/
      - name: Upload Asset
      # You may pin to the exact commit or the version.
      # uses: PeerXu/upload-asset@ac15234d94a4bfc9b33e1e98573fb470553ed809
        uses: PeerXu/upload-asset@v1
        with:
          # which file to upload
          file: android/app/build/outputs/apk/release/app-release.apk
          # file suffix
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
